name: Playwright Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  playwright:
    name: Playwright Tests
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright/python:v1.55.0-noble
      options: --user 1001

    steps:
      - uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
          python -m playwright install

      - name: Run tests
        run: pytest
